services:
  - type: web
    name: firewatch
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.11.0
